services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8001:80
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
    environment:
      MYSQL_ROOT_PASSWORD: auctions2023
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: auctions
      MYSQL_USER: root
      MYSQL_PASSWORD: auctions2023
networks:
  symfony: